Grants access to cnp-module-api-mgmt-subscription for pre
hmcts/sds-jenkins-config pull request #243
Opened 2024-01-16 16:04 UTC by jasonpaige

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [x] Does this PR introduce a breaking change

2024-01-16 16:10 UTC, zc-hmcts approved these changes

2024-01-17 09:42 UTC, andywilkinshmcts approved these changes

2024-01-17 09:51 UTC, timja requested changes
cnp-module's shouldn't be in a per app repo, unless testing a pre-release, move to the global.json file please

2024-01-17 11:22 UTC, timja approved these changes

2024-01-17 11:22 UTC, merged

2024-01-17 11:22 UTC, timja approved these changes